# Title: playbook.yml
# Date: 07/03/2017
# Author: Joseph J. Simpson
# Purpose: Set up a Centos 6.6 Box
# Version 0.1.0
# License:
#   playbook.yml Provision a CentOS 6.6 Q1 machine
#   Copyright (C) 2017  Joseph J. Simpson
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#

---
- name: Q1 CentOS 6.6 setup
  hosts: default
  tasks:
  # Make sure the ansible.cnf file exists and set to prompt for sudo
  # password -- vagrant in this case.
  - name: Print message
    debug: msg="Beginning of CentOS 6.6 configuration Ansible script."

  - name: Print Lab 1a group add message
    debug: msg="Add a new group, admin, to the system."

  - name: Add group admin
    command: /usr/sbin/groupadd admin
    become: true
    become_method: sudo
    become_user: root

  - name: Print Lab 1a users add message
    debug: msg="Add two new users to the system; q1u1, q2u2."

  - name: Add user q1u1
    command: /usr/sbin/useradd -c "Q1C6 User1" -G admin q1u1
    become: true
    become_method: sudo
    become_user: root

  - name: Add user q1u2
    command: /usr/sbin/useradd -c "Q1C6 User2" -G admin q1u2
    become: true
    become_method: sudo
    become_user: root

  - name: Install th libselinux-python package
    yum: name=libselinux-python state=installed
    become: true
    become_method: sudo
    become_user: root

  - name: Add ssh public key to q1u1 and q1u2, no password
    debug: msg="Add public key to the  q1u1, q2u2 accounts."

  - name: Make .ssh directory for user q1u1
    file: path=/home/q1u1/.ssh state=directory owner=q1u1 group=q1u1 mode=0700
    become: true
    become_method: sudo
    become_user: root

  - name: Make .ssh directory for user q1u2
    copy: src=authorized_keys dest=/home/q1u1/.ssh owner=q1u1 group=q1u1 mode=0600
    become: true
    become_method: sudo
    become_user: root
